<template>
  <div class="relative w-full max-w-[500px] h-[640px] bg-white rounded-[4px] shadow-2xl overflow-hidden font-mono transform rotate-1 transition-transform duration-500 hover:rotate-0">
    <!-- 纸张纹理背景（横线） -->
    <div class="absolute inset-0 paper-lines pointer-events-none"></div>
    
    <!-- 左侧装订孔 -->
    <div class="absolute left-0 top-0 bottom-0 w-12 border-r border-red-100/50 flex flex-col justify-evenly py-4 z-10 bg-white/5">
      <div v-for="n in 12" :key="n" class="w-3 h-3 rounded-full bg-gray-200/50 mx-auto shadow-inner"></div>
    </div>

    <!-- 内容区域 -->
    <div class="relative h-full overflow-hidden p-8 pl-20 text-gray-800 text-[13px] leading-[2rem]">
      <!-- 页眉 -->
      <div class="flex justify-between text-gray-400 mb-6 uppercase tracking-widest text-[10px] border-b border-gray-100 pb-2">
        <span>Generated by EduNinja AI</span>
        <span>2024-05-15</span>
      </div>

      <div class="space-y-0 relative z-10 script-content font-mono">
        <!-- 标题 -->
        <div class="text-center mb-6">
          <div class="font-bold uppercase tracking-widest text-lg text-black border-2 border-black inline-block px-4 py-1 transform -rotate-1">
            PERSONALIZED STUDY PLAN
          </div>
        </div>

        <!-- 目标概览 -->
        <div class="mb-6 grid grid-cols-2 gap-4 text-[11px] uppercase tracking-wide text-gray-500">
          <div>
            <span class="block text-gray-300">Target Subject</span>
            <span class="text-black font-bold">IB Biology HL</span>
          </div>
          <div class="text-right">
            <span class="block text-gray-300">Current Level</span>
            <span class="text-black font-bold">Level 5 ➔ Aiming for 7</span>
          </div>
        </div>

        <!-- 计划内容 -->
        <div class="space-y-4">
          <!-- 阶段 1 -->
          <div class="relative pl-4 border-l-2 border-blue-200">
            <div class="font-bold text-blue-600 uppercase text-[11px] mb-1">Phase 1: Concept Mastery</div>
            <p class="text-gray-600 leading-relaxed">
              Focus on <span class="bg-yellow-100 px-1">Topic 7 & 11</span>. 
              Review DNA replication mechanisms and kidney function details.
            </p>
          </div>

          <!-- 阶段 2 -->
          <div class="relative pl-4 border-l-2 border-green-200">
            <div class="font-bold text-green-600 uppercase text-[11px] mb-1">Phase 2: Paper Strategy</div>
            <p class="text-gray-600 leading-relaxed">
              Practice Data Based Questions (DBQs). 
              Target: Improve Paper 2 Section B essay structure on <span class="italic">Genetics</span>.
            </p>
          </div>

          <!-- 阶段 3 -->
          <div class="relative pl-4 border-l-2 border-purple-200">
            <div class="font-bold text-purple-600 uppercase text-[11px] mb-1">Phase 3: Final Sprint</div>
            <p class="text-gray-600 leading-relaxed">
              Full timed mock exam (Paper 1 & 2). 
              Review definitions for "Explain" vs "Describe" command terms.
            </p>
          </div>
        </div>

        <!-- 底部签名/印章 -->
        <div class="mt-8 flex justify-end items-center gap-2 opacity-80">
          <div class="text-[10px] text-right text-gray-400 uppercase tracking-widest">
            Plan Status<br>
            <span class="text-green-600 font-bold text-xs">READY TO EXECUTE</span>
          </div>
          <div class="w-8 h-8 rounded-full border-2 border-green-600 text-green-600 flex items-center justify-center font-bold text-[10px] transform rotate-12">
            AI
          </div>
        </div>
      </div>
    </div>

    <!-- 底部渐变遮罩，模拟纸张长度限制 -->
    <div class="absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-white to-transparent pointer-events-none z-20"></div>
  </div>
</template>

<script setup>
// 无需逻辑，纯展示组件
</script>

<style scoped>
/* 导入 Courier Prime 字体或使用系统等宽字体 */
@import url('https://fonts.googleapis.com/css2?family=Courier+Prime:ital,wght@0,400;0,700;1,400&display=swap');

.font-mono {
  font-family: 'Courier Prime', 'Courier New', Courier, monospace;
}

/* 纸张横线效果 */
.paper-lines {
  background-image: linear-gradient(
    to bottom,
    transparent 0%,
    transparent calc(2rem - 1px),
    #e5e7eb calc(2rem - 1px),
    #e5e7eb 2rem
  );
  background-size: 100% 2rem;
  /* 调整背景位置以匹配文字行高 */
  background-position: 0 0.5rem; 
}

/* 确保文字落在横线上 */
.script-content {
  line-height: 2rem;
}

/* 阴影优化 */
.shadow-2xl {
  box-shadow: 
    0 25px 50px -12px rgba(0, 0, 0, 0.15),
    0 0 15px rgba(0,0,0,0.05);
}
</style>
